### ISSUE TITLE
ShowerParticleList.h missing

### ISSUE THREAD

**Issue by miguelmf** [IceCube-SPNO/corsika_reader#12]
Hello,

The example in /share/examples/cpp/example_1 is not working because there's no ShowerParticleList.h. Here's the error:
```

fatal error: corsika/ShowerParticleList.h: No such file or directory
compilation terminated.
```

I'm using the tagged version.

**Comment by javierggt** [comment]
Hi Miguel, 

Sorry about that.  We started making some big changes which include name changes. Right before those changes I created a tag called v0. That should work.

**Comment by miguelmf** [comment]
Hey,

Thanks for the prompt reply!

I'm using the v0 release. It does not work. Are you sure it should be working? It may be something I'm missing, but there's no ShowerParticleList.h there.

**Comment by javierggt** [comment]
Ah, I see you say you used the tagged version. You mean v0?

**Comment by miguelmf** [comment]
@javierggt yes.

**Comment by javierggt** [comment]
I will check. Most probably it got broken. I'll get back to you later in the afternoon.

**Comment by miguelmf** [comment]
@javierggt, did you manage to check what happened with the ShowerParticleList.h file?

**Comment by javierggt** [comment]
Indeed there was a problem. The way to iterate over particles changed and the test was not updated. It will still change in the trunk. Sorry about that.

I just checked in some fixes for that. I also fixed some other things in building the test.

**Comment by miguelmf** [comment]
Thanks for this newest version. Sadly, it has another problem:

```
make[2]: *** No rule to make target '/home/me/corsika_reader-0.1/lib/libCorsikaReader.dylib', needed by 'corsika_example_1'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/corsika_example_1.dir/all' failed
make[1]: *** [CMakeFiles/corsika_example_1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by miguelmf** [comment]
Hello,

Sorry to bother you but, could you reproduce the error?

**Comment by javierggt** [comment]
Hi,

Yes. That is a bug and you can fix it in your working copy by doing what you did. I will commit a better fix for the future, but that's it.
