### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ddelventhal** [IceCube-SPNO/corsika_reader#9]
Would it be sufficient just to define a few global functions that print to stdout like the following?
log_info(...)
log_warning(...)
log_error(...)

Or maybe would we also want to print the source file and line number?

**Comment by javierggt** [comment]
I think file and line number is good.

I haven't thought about this much, but I would prefer something that could be channeled to standard I3 loggers. The minimum possible.

**Comment by dsschult** [comment]
@javierggt 
Is the goal to have this be an optional I3 project, or something installed separately and then used by I3 projects?

If the latter, it's almost impossible to directly hook into I3 logging.  But you can make an API for other code to "catch" the log messages and reformat them to I3.

**Comment by javierggt** [comment]
Yes, here: http://code.icecube.wisc.edu/projects/icecube/browser/IceCube/sandbox/jgonzalez/i3corsika

The way I see it, whichever class that uses the reader can add a call back that routes things to the I3 loggers.

**Comment by ddelventhal** [comment]
I defined three macros (corsika_log_info, corsika_log_error, corsika_log_fatal). Currently they just print out the error message, file name, line, and function name to stdout.
It should be trivial to have these macros call the i3 logging functions instead.
